version: "3.1"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: crypto_scope
    network_mode: host
    volumes:
      - ./.db-data:/var/lib/postgresql/data
